version: '3.7'
services:
    redis:
        image: redis
        ports:
            - '6379:6379'
    celery:
        build: celery
        command: poetry run celery -A tasks worker --loglevel=info
        depends_on:
            - redis
        volumes:
            - ./celery:/celery
